### ISSUE TITLE
-std=c++17?

### ISSUE THREAD

**Issue by krobasky** [xu-hao/datatrans#4]
It looks like the hatteras c++ compiler is pre-standard: g++ (GCC) v4.4.7, (c) 2010
Where are you picking up a c++17 standard compiler?
Should we put in a ticket at help.renci.org to get that installed on hatteras, and also on anylogic.renci.org?

**Comment by xu-hao** [comment]
you can use c++11 or c++14. I'll clarify this on the documentation.

**Comment by xu-hao** [comment]
c++0x should work for your g++ version.
